/**
 * 注释检查器钩子 - 防止 AI 生成过多注释
 * Comment checker hook - Prevents AI from generating excessive comments
 * 
 * 此钩子检查 Write/Edit/MultiEdit 工具生成的代码注释质量
 * This hook checks the quality of code comments generated by Write/Edit/MultiEdit tools
 * 
 * 检查规则：
 * Check rules:
 * - BDD 注释（//#given, //#when, //#then）允许 / BDD comments allowed
 * - 必要的注释（复杂算法、安全相关、性能优化）允许 / Necessary comments allowed
 * - 不必要的注释会触发警告 / Unnecessary comments trigger warnings
 * 
 * 违规处理：
 * Violation handling:
 * - 在工具输出中追加警告消息 / Append warning message to tool output
 * - 要求 AI 解释或删除注释 / Require AI to justify or remove comments
 * - 强制 AI 编写自解释代码 / Force AI to write self-documenting code
 */
import type { PendingCall } from "./types"
import { runCommentChecker, getCommentCheckerPath, startBackgroundInit, type HookInput } from "./cli"
import type { CommentCheckerConfig } from "../../config/schema"

import * as fs from "fs"
import { existsSync } from "fs"
import { tmpdir } from "os"
import { join } from "path"

const DEBUG = process.env.COMMENT_CHECKER_DEBUG === "1"
const DEBUG_FILE = join(tmpdir(), "comment-checker-debug.log")

function debugLog(...args: unknown[]) {
  if (DEBUG) {
    const msg = `[${new Date().toISOString()}] [comment-checker:hook] ${args.map(a => typeof a === 'object' ? JSON.stringify(a, null, 2) : String(a)).join(' ')}\n`
    fs.appendFileSync(DEBUG_FILE, msg)
  }
}

// 待处理的工具调用缓存（用于关联 PreToolUse 和 PostToolUse）
// Pending tool call cache (for correlating PreToolUse and PostToolUse)
const pendingCalls = new Map<string, PendingCall>()
const PENDING_CALL_TTL = 60_000

let cliPathPromise: Promise<string | null> | null = null
let cleanupIntervalStarted = false

/**
 * 清理过期的待处理调用
 * Cleans up expired pending calls
 */
function cleanupOldPendingCalls(): void {
  const now = Date.now()
  for (const [callID, call] of pendingCalls) {
    if (now - call.timestamp > PENDING_CALL_TTL) {
      pendingCalls.delete(callID)
    }
  }
}

/**
 * 创建注释检查器钩子
 * Creates comment checker hooks
 * 
 * 返回 PreToolUse 和 PostToolUse 钩子，用于检查代码注释质量
 * Returns PreToolUse and PostToolUse hooks for checking code comment quality
 * 
 * 工作流程：
 * Workflow:
 * 1. PreToolUse: 捕获 Write/Edit/MultiEdit 工具的输入参数 / Capture tool input parameters
 * 2. PostToolUse: 检查生成的代码注释 / Check generated code comments
 * 3. 如果检测到注释，注入警告消息 / If comments detected, inject warning message
 * 
 * CLI 集成：
 * CLI integration:
 * - 使用外部 CLI 工具进行注释检查 / Uses external CLI tool for comment checking
 * - 支持自定义提示词 / Supports custom prompts
 * - 如果 CLI 不可用，静默跳过检查 / Silently skips if CLI unavailable
 * 
 * @param config - 注释检查器配置 / Comment checker configuration
 * @returns 包含 PreToolUse 和 PostToolUse 钩子的对象 / Object containing PreToolUse and PostToolUse hooks
 */
export function createCommentCheckerHooks(config?: CommentCheckerConfig) {
  debugLog("createCommentCheckerHooks called", { config })

  if (!cleanupIntervalStarted) {
    cleanupIntervalStarted = true
    setInterval(cleanupOldPendingCalls, 10_000)
  }
  
  // Start background CLI initialization (may trigger lazy download)
  startBackgroundInit()
  cliPathPromise = getCommentCheckerPath()
  cliPathPromise.then(path => {
    debugLog("CLI path resolved:", path || "disabled (no binary)")
  }).catch(err => {
    debugLog("CLI path resolution error:", err)
  })
  
  return {
    "tool.execute.before": async (
      input: { tool: string; sessionID: string; callID: string },
      output: { args: Record<string, unknown> }
    ): Promise<void> => {
      debugLog("tool.execute.before:", { tool: input.tool, callID: input.callID, args: output.args })
      
      const toolLower = input.tool.toLowerCase()
      if (toolLower !== "write" && toolLower !== "edit" && toolLower !== "multiedit") {
        debugLog("skipping non-write/edit tool:", toolLower)
        return
      }

      const filePath = (output.args.filePath ?? output.args.file_path ?? output.args.path) as string | undefined
      const content = output.args.content as string | undefined
      const oldString = output.args.oldString ?? output.args.old_string as string | undefined
      const newString = output.args.newString ?? output.args.new_string as string | undefined
      const edits = output.args.edits as Array<{ old_string: string; new_string: string }> | undefined

      debugLog("extracted filePath:", filePath)

      if (!filePath) {
        debugLog("no filePath found")
        return
      }

      debugLog("registering pendingCall:", { callID: input.callID, filePath, tool: toolLower })
      pendingCalls.set(input.callID, {
        filePath,
        content,
        oldString: oldString as string | undefined,
        newString: newString as string | undefined,
        edits,
        tool: toolLower as "write" | "edit" | "multiedit",
        sessionID: input.sessionID,
        timestamp: Date.now(),
      })
    },

    "tool.execute.after": async (
      input: { tool: string; sessionID: string; callID: string },
      output: { title: string; output: string; metadata: unknown }
    ): Promise<void> => {
      debugLog("tool.execute.after:", { tool: input.tool, callID: input.callID })
      
      const pendingCall = pendingCalls.get(input.callID)
      if (!pendingCall) {
        debugLog("no pendingCall found for:", input.callID)
        return
      }

      pendingCalls.delete(input.callID)
      debugLog("processing pendingCall:", pendingCall)

      // Only skip if the output indicates a tool execution failure
      const outputLower = output.output.toLowerCase()
      const isToolFailure = 
        outputLower.includes("error:") || 
        outputLower.includes("failed to") ||
        outputLower.includes("could not") ||
        outputLower.startsWith("error")
      
      if (isToolFailure) {
        debugLog("skipping due to tool failure in output")
        return
      }

      try {
        // Wait for CLI path resolution
        const cliPath = await cliPathPromise
        
        if (!cliPath || !existsSync(cliPath)) {
          // CLI not available - silently skip comment checking
          debugLog("CLI not available, skipping comment check")
          return
        }
        
        // CLI mode only
        debugLog("using CLI:", cliPath)
        await processWithCli(input, pendingCall, output, cliPath, config?.custom_prompt)
      } catch (err) {
        debugLog("tool.execute.after failed:", err)
      }
    },
  }
}

async function processWithCli(
  input: { tool: string; sessionID: string; callID: string },
  pendingCall: PendingCall,
  output: { output: string },
  cliPath: string,
  customPrompt?: string
): Promise<void> {
  debugLog("using CLI mode with path:", cliPath)
  
  const hookInput: HookInput = {
    session_id: pendingCall.sessionID,
    tool_name: pendingCall.tool.charAt(0).toUpperCase() + pendingCall.tool.slice(1),
    transcript_path: "",
    cwd: process.cwd(),
    hook_event_name: "PostToolUse",
    tool_input: {
      file_path: pendingCall.filePath,
      content: pendingCall.content,
      old_string: pendingCall.oldString,
      new_string: pendingCall.newString,
      edits: pendingCall.edits,
    },
  }
  
  const result = await runCommentChecker(hookInput, cliPath, customPrompt)
  
  if (result.hasComments && result.message) {
    debugLog("CLI detected comments, appending message")
    output.output += `\n\n${result.message}`
  } else {
    debugLog("CLI: no comments detected")
  }
}
